import { City, Place, Review, User, Badge, Achievement } from './types';

export const cities: City[] = [
  {
    id: 'surabaya',
    name: 'Surabaya',
    image: 'https://images.unsplash.com/photo-1588668214407-6ea9a6d8c272?w=800&q=80',
    description: 'Kota Pahlawan dengan kuliner legendaris dan wisata sejarah',
    placeCount: 45,
  },
  {
    id: 'malang',
    name: 'Malang',
    image: 'https://images.unsplash.com/photo-1592364395653-83e648b20cc2?w=800&q=80',
    description: 'Kota sejuk dengan pemandangan alam dan kuliner khas',
    placeCount: 52,
  },
  {
    id: 'banyuwangi',
    name: 'Banyuwangi',
    image: 'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?w=800&q=80',
    description: 'The Sunrise of Java dengan keindahan alam eksotis',
    placeCount: 38,
  },
  {
    id: 'batu',
    name: 'Batu',
    image: 'https://images.unsplash.com/photo-1596402184320-417e7178b2cd?w=800&q=80',
    description: 'Kota wisata dengan berbagai wahana dan agrowisata',
    placeCount: 35,
  },
  {
    id: 'jember',
    name: 'Jember',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    description: 'Kota karnaval dengan pantai dan pegunungan indah',
    placeCount: 28,
  },
  {
    id: 'probolinggo',
    name: 'Probolinggo',
    image: 'https://images.unsplash.com/photo-1588668214407-6ea9a6d8c272?w=800&q=80',
    description: 'Gerbang menuju Gunung Bromo yang megah',
    placeCount: 22,
  },
];

export const places: Place[] = [
  // Wisata
  {
    id: '1',
    name: 'Tumpak Sewu Waterfall',
    slug: 'tumpak-sewu-waterfall',
    description: 'Air terjun spektakuler dengan panorama 180 derajat yang memukau',
    longDescription: 'Dikenal sebagai "Coban Sewu" air terjun dengan ribuan aliran yang menakjubkan. Terletak di lereng Gunung Semeru, air terjun ini menawarkan pemandangan yang spektakuler dan pengalaman petualangan yang tak terlupakan. Perjalanan menuju dasar air terjun membutuhkan trekking sekitar 45 menit melalui tangga bambu dan penyeberangan sungai.',
    category: 'wisata',
    cityId: 'malang',
    cityName: 'Lumajang, East Java',
    image: 'https://images.unsplash.com/photo-1533587851505-d119e13fa0d7?w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1533587851505-d119e13fa0d7?w=800&q=80',
      'https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?w=800&q=80',
      'https://images.unsplash.com/photo-1475924156734-496f6cac6ec1?w=800&q=80',
    ],
    rating: 4.8,
    reviewCount: 1243,
    address: 'Desa Sidomulyo, Kec. Pronojiwo, Lumajang',
    coordinates: { lat: -8.2301, lng: 112.9169 },
    operationalHours: '07:00 - 15:00',
    priceRange: 'Rp 20.000 / person',
    estimatedDuration: '3-4 hours',
    difficulty: 'Challenging Hike',
    isMustVisit: true,
    tags: ['Waterfall', 'Hiking', 'Nature'],
  },
  {
    id: '2',
    name: 'Kawah Ijen Blue Fire',
    slug: 'kawah-ijen-blue-fire',
    description: 'Fenomena api biru langka dan danau kawah asam terbesar di dunia',
    longDescription: 'Kawah Ijen menawarkan pengalaman mendaki yang unik dengan fenomena blue fire yang hanya bisa dilihat saat malam hari. Danau kawah berwarna tosca yang menakjubkan menjadi pemandangan utama saat matahari terbit.',
    category: 'wisata',
    cityId: 'banyuwangi',
    cityName: 'Banyuwangi',
    image: 'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?w=800&q=80',
    rating: 4.9,
    reviewCount: 2156,
    address: 'Kawah Ijen, Licin, Banyuwangi',
    operationalHours: '00:00 - 12:00',
    priceRange: 'Rp 100k / person',
    estimatedDuration: '6-8 hours',
    difficulty: 'Moderate',
    isMustVisit: true,
    tags: ['Volcano', 'Hiking', 'Sunrise'],
  },
  {
    id: '3',
    name: 'Teluk Hijau (Green Bay)',
    slug: 'teluk-hijau-green-bay',
    description: 'Pantai tersembunyi dengan air hijau zamrud yang jernih',
    category: 'wisata',
    cityId: 'banyuwangi',
    cityName: 'Banyuwangi',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80',
    rating: 4.7,
    reviewCount: 892,
    address: 'Taman Nasional Meru Betiri, Banyuwangi',
    operationalHours: '07:00 - 17:00',
    priceRange: 'Rp 15k / person',
    isMustVisit: true,
    tags: ['Beach', 'Hidden Gem', 'Nature'],
  },
  {
    id: '4',
    name: 'Pantai Papuma',
    slug: 'pantai-papuma',
    description: 'Pantai eksotis dengan tebing karang dan pasir putih',
    category: 'wisata',
    cityId: 'jember',
    cityName: 'Jember',
    image: 'https://images.unsplash.com/photo-1519046904884-53103b34b206?w=800&q=80',
    rating: 4.5,
    reviewCount: 567,
    address: 'Lojejer, Wuluhan, Jember',
    operationalHours: '24 Hours',
    priceRange: 'Rp 10k / person',
    isMustVisit: false,
    tags: ['Beach', 'Sunset', 'Camping'],
  },
  {
    id: '5',
    name: 'Gunung Bromo',
    slug: 'gunung-bromo',
    description: 'Gunung berapi aktif dengan pemandangan sunrise legendaris',
    category: 'wisata',
    cityId: 'probolinggo',
    cityName: 'Probolinggo',
    image: 'https://images.unsplash.com/photo-1588668214407-6ea9a6d8c272?w=800&q=80',
    rating: 4.9,
    reviewCount: 5420,
    address: 'Taman Nasional Bromo Tengger Semeru',
    operationalHours: '24 Hours',
    priceRange: 'Rp 35k / person',
    estimatedDuration: '4-6 hours',
    isMustVisit: true,
    tags: ['Volcano', 'Sunrise', 'Iconic'],
  },
  {
    id: '6',
    name: 'Pulau Merah Sunset',
    slug: 'pulau-merah-sunset',
    description: 'Pantai surfing dengan sunset spektakuler',
    category: 'wisata',
    cityId: 'banyuwangi',
    cityName: 'Banyuwangi',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    rating: 4.6,
    reviewCount: 1023,
    address: 'Sumberagung, Pesanggaran, Banyuwangi',
    operationalHours: '06:00 - 18:00',
    priceRange: 'Rp 10k / person',
    isMustVisit: true,
    tags: ['Beach', 'Surfing', 'Sunset'],
  },
  {
    id: '7',
    name: 'Coban Rondo',
    slug: 'coban-rondo',
    description: 'Air terjun cantik di kawasan hutan pinus sejuk',
    category: 'wisata',
    cityId: 'malang',
    cityName: 'Malang',
    image: 'https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?w=800&q=80',
    rating: 4.4,
    reviewCount: 1567,
    address: 'Pandesari, Pujon, Malang',
    operationalHours: '08:00 - 16:00',
    priceRange: 'Rp 25k / person',
    isMustVisit: false,
    tags: ['Waterfall', 'Family Friendly'],
  },
  {
    id: '8',
    name: 'Jatim Park 2',
    slug: 'jatim-park-2',
    description: 'Taman wisata edukasi dengan museum satwa terlengkap',
    category: 'wisata',
    cityId: 'batu',
    cityName: 'Batu',
    image: 'https://images.unsplash.com/photo-1596402184320-417e7178b2cd?w=800&q=80',
    rating: 4.5,
    reviewCount: 3421,
    address: 'Jl. Oro-oro Ombo No. 9, Batu',
    operationalHours: '09:00 - 17:00',
    priceRange: 'Rp 120k / person',
    isMustVisit: true,
    tags: ['Theme Park', 'Family', 'Education'],
  },
  // Kuliner
  {
    id: '9',
    name: 'Rawon Nguling',
    slug: 'rawon-nguling',
    description: 'Rawon legendaris dengan kuah hitam pekat dan daging empuk',
    category: 'kuliner',
    cityId: 'surabaya',
    cityName: 'Surabaya',
    image: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=800&q=80',
    rating: 4.7,
    reviewCount: 2341,
    address: 'Jl. Embong Malang No. 78, Surabaya',
    operationalHours: '07:00 - 21:00',
    priceRange: 'Rp 25k - 50k',
    isMustVisit: true,
    tags: ['Traditional', 'Beef', 'Iconic'],
  },
  {
    id: '10',
    name: 'Rujak Cingur Pak Gendut',
    slug: 'rujak-cingur-pak-gendut',
    description: 'Rujak cingur otentik dengan bumbu petis khas Surabaya',
    category: 'kuliner',
    cityId: 'surabaya',
    cityName: 'Surabaya',
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80',
    rating: 4.6,
    reviewCount: 1892,
    address: 'Jl. Kupang Baru, Surabaya',
    operationalHours: '10:00 - 20:00',
    priceRange: 'Rp 20k - 35k',
    isMustVisit: true,
    tags: ['Traditional', 'Unique', 'Spicy'],
  },
  {
    id: '11',
    name: 'Bakso President Malang',
    slug: 'bakso-president-malang',
    description: 'Bakso jumbo legendaris dengan berbagai varian isian',
    category: 'kuliner',
    cityId: 'malang',
    cityName: 'Malang',
    image: 'https://images.unsplash.com/photo-1555126634-323283e090fa?w=800&q=80',
    rating: 4.5,
    reviewCount: 3456,
    address: 'Jl. Semeru No. 24, Malang',
    operationalHours: '09:00 - 21:00',
    priceRange: 'Rp 15k - 40k',
    isMustVisit: true,
    tags: ['Meatball', 'Popular', 'Affordable'],
  },
  {
    id: '12',
    name: 'Warung Sego Tempong',
    slug: 'warung-sego-tempong',
    description: 'Nasi tempong khas Banyuwangi dengan sambal pedas menggugah selera',
    category: 'kuliner',
    cityId: 'banyuwangi',
    cityName: 'Banyuwangi',
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=800&q=80',
    rating: 4.6,
    reviewCount: 1234,
    address: 'Jl. Ahmad Yani, Banyuwangi',
    operationalHours: '06:00 - 22:00',
    priceRange: 'Rp 15k - 25k',
    isMustVisit: true,
    tags: ['Traditional', 'Spicy', 'Rice'],
  },
  {
    id: '13',
    name: 'Pecel Rawon Bu Pangat',
    slug: 'pecel-rawon-bu-pangat',
    description: 'Kombinasi unik pecel dan rawon dalam satu porsi',
    category: 'kuliner',
    cityId: 'surabaya',
    cityName: 'Surabaya',
    image: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=800&q=80',
    rating: 4.4,
    reviewCount: 987,
    address: 'Jl. Raya Darmo, Surabaya',
    operationalHours: '08:00 - 15:00',
    priceRange: 'Rp 25k - 45k',
    isMustVisit: false,
    tags: ['Traditional', 'Unique'],
  },
  {
    id: '14',
    name: 'Sate Klopo Ondomohen',
    slug: 'sate-klopo-ondomohen',
    description: 'Sate ayam dengan taburan kelapa parut yang gurih',
    category: 'kuliner',
    cityId: 'surabaya',
    cityName: 'Surabaya',
    image: 'https://images.unsplash.com/photo-1529563021893-cc83c992d75d?w=800&q=80',
    rating: 4.7,
    reviewCount: 2156,
    address: 'Jl. Ondomohen, Surabaya',
    operationalHours: '17:00 - 23:00',
    priceRange: 'Rp 30k - 50k',
    isMustVisit: true,
    tags: ['Satay', 'Traditional', 'Evening'],
  },
  {
    id: '15',
    name: 'Toko Oen',
    slug: 'toko-oen',
    description: 'Es krim dan kue legendaris sejak 1930',
    category: 'kuliner',
    cityId: 'malang',
    cityName: 'Malang',
    image: 'https://images.unsplash.com/photo-1551024601-bec78aea704b?w=800&q=80',
    rating: 4.6,
    reviewCount: 4523,
    address: 'Jl. Basuki Rahmat No. 5, Malang',
    operationalHours: '10:00 - 22:00',
    priceRange: 'Rp 30k - 80k',
    isMustVisit: true,
    tags: ['Ice Cream', 'Heritage', 'Dessert'],
  },
  {
    id: '16',
    name: 'Warung Leko',
    slug: 'warung-leko',
    description: 'Masakan tradisional Madura dengan cita rasa autentik',
    category: 'kuliner',
    cityId: 'surabaya',
    cityName: 'Surabaya',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&q=80',
    rating: 4.3,
    reviewCount: 756,
    address: 'Jl. Kedungdoro, Surabaya',
    operationalHours: '10:00 - 21:00',
    priceRange: 'Rp 20k - 40k',
    isMustVisit: false,
    tags: ['Traditional', 'Madura'],
  },
];

export const reviews: Review[] = [
  {
    id: '1',
    placeId: '1',
    userId: '1',
    userName: 'Aria Kurniawan',
    userAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&q=80',
    userLevel: 12,
    rating: 5,
    comment: 'The descent is steep but every step is worth it. Standing at the base feels like being in another world. The mist from the waterfall creates an ethereal atmosphere. Must bring proper hiking shoes and be prepared for slippery paths.',
    photos: [
      'https://images.unsplash.com/photo-1533587851505-d119e13fa0d7?w=400&q=80',
    ],
    createdAt: '2024-03-15',
  },
  {
    id: '2',
    placeId: '1',
    userId: '2',
    userName: 'Fransiska Dea',
    userAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&q=80',
    userLevel: 8,
    rating: 5,
    comment: 'Absolutely breathtaking! The hike down is challenging but the view from the bottom is unreal. Bring waterproof gear!',
    createdAt: '2024-03-10',
  },
  {
    id: '3',
    placeId: '1',
    userId: '3',
    userName: 'Trengginas Waryanto',
    userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&q=80',
    userLevel: 15,
    rating: 4,
    comment: 'Beautiful waterfall, but can get crowded on weekends. Recommend coming early morning for the best experience and photos.',
    createdAt: '2024-03-05',
  },
];

export const badges: Badge[] = [
  {
    id: '1',
    name: 'Surabaya Foodie',
    description: 'Visited 10 culinary spots in Surabaya',
    icon: '🍜',
  },
  {
    id: '2',
    name: 'Mountain King',
    description: 'Conquered 5 mountains in East Java',
    icon: '⛰️',
  },
  {
    id: '3',
    name: 'Night Owl',
    description: 'Visited 3 night destinations',
    icon: '🦉',
  },
  {
    id: '4',
    name: 'Beach Lover',
    description: 'Explored 10 beaches',
    icon: '🏖️',
  },
  {
    id: '5',
    name: 'Explorer',
    description: 'Visited all 6 major cities',
    icon: '🧭',
  },
  {
    id: '6',
    name: 'Mist Weaver',
    description: 'Visited 5 waterfalls',
    icon: '💧',
  },
  {
    id: '7',
    name: 'Cascade Seeker',
    description: 'Found 3 hidden waterfalls',
    icon: '🌊',
  },
];

export const achievements: Achievement[] = [
  {
    id: '1',
    name: 'First Steps',
    description: 'Visit your first destination',
    icon: '👣',
    requirement: 1,
    current: 1,
    isUnlocked: true,
  },
  {
    id: '2',
    name: 'Explorer',
    description: 'Visit 10 destinations',
    icon: '🗺️',
    requirement: 10,
    current: 8,
    isUnlocked: false,
  },
  {
    id: '3',
    name: 'Reviewer',
    description: 'Write 5 reviews',
    icon: '✍️',
    requirement: 5,
    current: 5,
    isUnlocked: true,
  },
  {
    id: '4',
    name: 'Photographer',
    description: 'Share 20 photos',
    icon: '📸',
    requirement: 20,
    current: 15,
    isUnlocked: false,
  },
];

export const currentUser: User = {
  id: '1',
  name: 'Budi Explorer',
  email: 'budi@example.com',
  avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&q=80',
  level: 12,
  xp: 2450,
  xpToNextLevel: 3000,
  role: 'user',
  stats: {
    placesVisited: 42,
    reviewsWritten: 128,
    photosShared: 315,
  },
  badges: badges.slice(0, 4),
  visitedCities: ['surabaya', 'malang', 'banyuwangi'],
  favoriteCities: ['malang', 'batu'],
  joinedAt: '2023-06-15',
};

export const adminUser: User = {
  id: '2',
  name: 'Admin Wander',
  email: 'admin@wandereast.com',
  avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=200&q=80',
  level: 99,
  xp: 99999,
  xpToNextLevel: 100000,
  role: 'admin',
  stats: {
    placesVisited: 150,
    reviewsWritten: 0,
    photosShared: 0,
  },
  badges: [],
  visitedCities: [],
  favoriteCities: [],
  joinedAt: '2023-01-01',
};

export const recentExpeditions = [
  {
    id: '1',
    title: 'Checked in at Tumpak Sewu Waterfall',
    description: 'The descent is challenging but the view from the bottom is simply otherworldly. Pure magic in the heart of the jungle.',
    location: 'Lumajang',
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1533587851505-d119e13fa0d7?w=400&q=80',
  },
  {
    id: '2',
    title: 'Reviewed Madakaripura Waterfall',
    description: "Don't forget to rent a raincoat! The walk through the canyon is incredibly atmospheric.",
    location: 'Probolinggo',
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?w=400&q=80',
  },
];
